name:                volr
version:             0.1.0.0
github:              "volr/compiler"
license:             BSD3
author:              "Jens Egholm Pedersen"
maintainer:          "jensegholm@protonmail.com"
copyright:           "2018 Jens Egholm Pedersen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/futhark-backend#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl >= 2.2.1
  - containers >= 0.5.11.0


executables:
  futhark-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - volr

tests:
  futhark-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers >= 0.5.11.0
    - volr
    - hspec
    - mtl >= 2.2.1